import type { AppLanguage } from "@/types/language";

const en = {
  startTitle: "Expand your idea into an AI prompt", startSubtitle: "Your idea, ready for its next step.",
  workflow: { idea: "Your rough idea", prompt: "Expanded AI prompt", chatbot: "Your AI assistant" },
  expansionExample: { label: "Example expansion", badge: "Example", original: "Original idea", idea: "email asking for 2 extra days", title: "Expanded AI prompt", goalLabel: "Goal", goal: "Write a polite email asking for two extra days to finish a task.", detailsLabel: "Details", details: "Use [recipient], [task] and [current deadline] for missing facts. Keep the tone professional; do not invent a reason.", outputLabel: "Output", output: "Return a subject line and a concise email, ready to edit and send.", use: "Use this idea" },
  placeholderIdeas: ["email asking for two extra days", "meals for the week, low budget", "a topic I don't understand", "job interview next week", "a weekend trip with my family", "messy meeting notes to organize"],
  pauseExamples: "Pause examples", resumeExamples: "Resume examples",
  resultViews: "Prompt preview", yourPrompt: "Your prompt", exampleTab: "Example",
  optimize: "Optimize prompt", optimizing: "Optimizing...", optimizeHint: "Improve clarity and instructions",
  optimizeError: "Couldn't optimize this prompt. Your original is unchanged. Please try again.", optimizeScoreError: "Couldn't check this prompt before optimizing. Your original is unchanged. Please try again.", optimizeDone: "Prompt optimized. Your previous version is saved.",
  download: "Download prompt", copyError: "Could not copy. Select the prompt text to copy it manually.", word: "word", words: "words",
  title: "Expand your idea into an AI prompt", subtitle: "Your idea, ready for its next step.",
  idea: "Your rough idea", placeholder: "email asking for two extra days", create: "Expand my idea", guestCreate: "Sign in to expand my idea", generating: "Expanding your idea...",
  category: "Task type (optional)",
  checking: "Checking the details...", inspiration: "Starting ideas", matching: "Related ideas",
  refresh: "More ideas", details: "A few details about your idea", skip: "Use what I have", continue: "Expand my idea", custom: "Your own answer",
  audience: "Who is this for?", constraints: "Anything to include or avoid?", format: "What should the result look like?",
  context: "More details (optional)", result: "Your expanded AI prompt", portable: "Ready for your AI assistant", quality: "Quality check", qualityNote: "An estimate of prompt quality, not a guarantee of the answer.",
  save: "Save", saved: "Saved", copied: "Copied", copy: "Copy AI prompt", answer: "Was the AI's answer better?", yes: "Yes", no: "No", thanks: "Thanks for the feedback.",
  clarifyError: "Couldn't check for missing details. You can still expand your idea.", generateError: "Couldn't expand your idea. Please try again.",
  categories: { auto: "Any task", writing: "Emails & writing", coding: "Apps & computer code", research: "Learning & comparing", daily: "Home & planning", business: "Work & business", creative: "Stories & ideas" },
};
type Copy = typeof en;
const es: Copy = {
  startTitle: "Amplía tu idea en un prompt para IA", startSubtitle: "Tu idea, lista para el siguiente paso.",
  workflow: { idea: "Tu idea inicial", prompt: "Prompt ampliado", chatbot: "Tu asistente de IA" },
  expansionExample: { label: "Ejemplo de ampliación", badge: "Ejemplo", original: "Idea original", idea: "correo para pedir 2 días más", title: "Prompt ampliado", goalLabel: "Objetivo", goal: "Escribe un correo amable para pedir dos días más para terminar una tarea.", detailsLabel: "Detalles", details: "Usa [destinatario], [tarea] y [fecha límite actual] para los datos que falten. Mantén un tono profesional y no inventes un motivo.", outputLabel: "Resultado", output: "Devuelve un asunto y un correo breve, listo para editar y enviar.", use: "Usar esta idea" },
  placeholderIdeas: ["correo para pedir dos días más", "comidas semanales con poco presupuesto", "un tema que no entiendo", "entrevista de trabajo la próxima semana", "viaje de fin de semana en familia", "notas de reunión por organizar"],
  pauseExamples: "Pausar ejemplos", resumeExamples: "Reanudar ejemplos",
  resultViews: "Vista del prompt", yourPrompt: "Tu prompt", exampleTab: "Ejemplo",
  optimize: "Optimizar prompt", optimizing: "Optimizando...", optimizeHint: "Mejorar la claridad y las instrucciones",
  optimizeError: "No se pudo optimizar el prompt. El original no ha cambiado. Inténtalo de nuevo.", optimizeScoreError: "No se pudo revisar el prompt antes de optimizarlo. El original no ha cambiado. Inténtalo de nuevo.", optimizeDone: "Prompt optimizado. Tu versión anterior está guardada.",
  download: "Descargar prompt", copyError: "No se pudo copiar. Selecciona el texto del prompt para copiarlo manualmente.", word: "palabra", words: "palabras",
  title: "Amplía tu idea en un prompt para IA", subtitle: "Tu idea, lista para el siguiente paso.", idea: "Tu idea inicial", placeholder: "correo para pedir dos días más", create: "Ampliar mi idea", guestCreate: "Iniciar sesión y ampliar mi idea", generating: "Ampliando tu idea...", category: "Tipo de tarea (opcional)",
  checking: "Comprobando los detalles...", inspiration: "Ideas para empezar", matching: "Ideas relacionadas", refresh: "Más ideas", details: "Algunos detalles de tu idea", skip: "Usar lo que tengo", continue: "Ampliar mi idea", custom: "Tu propia respuesta",
  audience: "¿Para quién es?", constraints: "¿Qué incluir o evitar?", format: "¿Cómo debe ser el resultado?", context: "Más detalles (opcional)", result: "Tu prompt ampliado", portable: "Listo para tu asistente de IA", quality: "Revisión de calidad", qualityNote: "Una estimación de la calidad del prompt, no una garantía del resultado.",
  save: "Guardar", saved: "Guardado", copied: "Copiado", copy: "Copiar prompt", answer: "¿La respuesta de la IA fue mejor?", yes: "Sí", no: "No", thanks: "Gracias por tu opinión.", clarifyError: "No pudimos comprobar los detalles. Puedes preparar tu prompt igualmente.", generateError: "No se pudo ampliar tu idea. Inténtalo de nuevo.",
  categories: { auto: "Cualquier tarea", writing: "Correos y textos", coding: "Apps y programación", research: "Aprender y comparar", daily: "Hogar y planes", business: "Trabajo y negocios", creative: "Historias e ideas" },
};
const ru: Copy = {
  startTitle: "Превратите идею в подробный запрос для ИИ", startSubtitle: "Ваша идея, готовая к следующему шагу.",
  workflow: { idea: "Ваша черновая идея", prompt: "Подробный запрос", chatbot: "Ваш ИИ-помощник" },
  expansionExample: { label: "Пример расширения идеи", badge: "Пример", original: "Исходная идея", idea: "письмо с просьбой дать ещё 2 дня", title: "Подробный запрос для ИИ", goalLabel: "Цель", goal: "Напиши вежливое письмо с просьбой дать ещё два дня для завершения задачи.", detailsLabel: "Детали", details: "Для неизвестных данных используй [получатель], [задача] и [текущий срок]. Сохрани профессиональный тон, не придумывай причину.", outputLabel: "Результат", output: "Верни тему письма и короткий текст, готовый для редактирования и отправки.", use: "Использовать эту идею" },
  placeholderIdeas: ["письмо с просьбой дать ещё два дня", "недорогое меню на неделю", "тема, которую я не понимаю", "собеседование на следующей неделе", "поездка на выходные с семьёй", "разобрать заметки со встречи"],
  pauseExamples: "Приостановить примеры", resumeExamples: "Продолжить примеры",
  resultViews: "Просмотр запроса", yourPrompt: "Ваш запрос", exampleTab: "Пример",
  optimize: "Оптимизировать запрос", optimizing: "Оптимизация...", optimizeHint: "Улучшить ясность и инструкции",
  optimizeError: "Не удалось оптимизировать запрос. Исходный текст не изменён. Попробуйте ещё раз.", optimizeScoreError: "Не удалось проверить запрос перед оптимизацией. Исходный текст не изменён. Попробуйте ещё раз.", optimizeDone: "Запрос оптимизирован. Предыдущая версия сохранена.",
  download: "Скачать запрос", copyError: "Не удалось скопировать. Выделите текст запроса и скопируйте его вручную.", word: "слово", words: "слов",
  title: "Превратите идею в подробный запрос для ИИ", subtitle: "Ваша идея, готовая к следующему шагу.", idea: "Ваша черновая идея", placeholder: "письмо с просьбой дать ещё два дня", create: "Расширить мою идею", guestCreate: "Войти и расширить идею", generating: "Расширяем вашу идею...", category: "Тип задачи (необязательно)",
  checking: "Проверяем детали...", inspiration: "Идеи для начала", matching: "Похожие идеи", refresh: "Другие идеи", details: "Несколько деталей о вашей идее", skip: "Использовать то, что есть", continue: "Расширить мою идею", custom: "Свой ответ",
  audience: "Для кого это?", constraints: "Что включить или исключить?", format: "Каким должен быть результат?", context: "Больше деталей (необязательно)", result: "Ваш подробный запрос для ИИ", portable: "Готов для вашего ИИ-помощника", quality: "Проверка качества", qualityNote: "Оценка качества промпта, а не гарантия ответа.",
  save: "Сохранить", saved: "Сохранено", copied: "Скопировано", copy: "Копировать запрос", answer: "Ответ ИИ стал лучше?", yes: "Да", no: "Нет", thanks: "Спасибо за отзыв.", clarifyError: "Не удалось проверить детали. Вы всё равно можете подготовить запрос.", generateError: "Не удалось расширить идею. Попробуйте ещё раз.",
  categories: { auto: "Любая задача", writing: "Письма и тексты", coding: "Приложения и код", research: "Учёба и сравнение", daily: "Дом и планы", business: "Работа и бизнес", creative: "Истории и идеи" },
};
export function composerCopy(language: AppLanguage): Copy { return ({ en, es, ru })[language] ?? en; }
